baseURL = 'https://nspcc.io/'
languageCode = 'en-us'
title = 'Санкт-Петербургский Центр Компетенций Neo'
theme = "nspcc-theme"

# languages
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ru]
    languageName = "Russian"
    weight = 2

# social links
[[params.social]]
icon = "medium"
name = "@neospcc"
link = "https://medium.com/@neospcc"

[[params.social]]
icon = "twitter"
name = "@neospcc"
link = "https://twitter.com/neospcc"

[[params.social]]
icon = "github"
name = "GitHub"
link = "https://github.com/nspcc-dev"

[[params.social]]
icon = "youtube"
name = "YouTube"
link = "https://www.youtube.com/@neospcc5818"
